Repository i-aka5h/Hack-October, pull requests merged in 2022-10, with the labels that each got.

#22 Added two useful files in Python
  Programs/Python codes/colorama-module.py
  Programs/Python codes/gcd.py
Labels: hacktoberfest, hacktoberfest-accepted

#24 Create Battery Notifier.py
  Projects/Battery Notifier.py
Labels: hacktoberfest, hacktoberfest-accepted

#29 Added a weather project
  Projects/JavaScript/WeatherProject/app.js
  Projects/JavaScript/WeatherProject/index.html
  Projects/JavaScript/WeatherProject/style.css
Labels: hacktoberfest-accepted

#30 Create Website Blocker.py
  Programs/Python codes/Website Blocker.py
Labels: hacktoberfest-accepted

#34 Create Check Palindrome in 3 lines of code.js
  Programs/JavaScript Codes/Check Palindrome in 3 lines of code.js
Labels: hacktoberfest-accepted

#35 Create Beginner Snake Game.js
  Projects/JavaScript/Beginner Snake Game.js
Labels: hacktoberfest, hacktoberfest-accepted

#36 add a movie recommendation system project
  MachineLearningModels/movie-recommendation-system-project.ipynb
  MachineLearningModels/movies.csv
Labels: hacktoberfest, hacktoberfest-accepted

#38 create images_to_jpg_file_converter
  Programs/Python codes/convert_image_to_jpg_file.py
Labels: hacktoberfest-accepted

#39 Create Copy_List_with_Random _Pointer.java
  Programs/Java Codes/Copy_List_with_Random _Pointer.java
Labels: hacktoberfest-accepted

#43 iris flower image classification
  MachineLearningModels/IRIS_Classification.ipynb
Labels: hacktoberfest-accepted

#45 Created simple interest calculator using vanilla javascript
  Projects/JavaScript/SImpleinterestcalculator/index.css
  Projects/JavaScript/SImpleinterestcalculator/index.html
  Projects/JavaScript/SImpleinterestcalculator/index.js
Labels: hacktoberfest-accepted

#50 Added snake game
  Programs/Python codes/snake-game.py
Labels: hacktoberfest, hacktoberfest-accepted

#54 Created a Contribue.md file for the steps on how to contribute
  Contribute.md
Labels: hacktoberfest-accepted

#53 Added Moore's Algorithm
  Programs/Java Codes/MooresAlgo.java
Labels: hacktoberfest-accepted

#58 Added KMeans Clustering code
  Machine-Learning-Models/KMeans Clustering/kmeans_clustering.py
Labels: hacktoberfest, hacktoberfest-accepted

#77 Resolved issue #74
  Programs/Python codes/FaceDetection.py
  Programs/Python codes/face2.jpg
  Programs/Python codes/faceDetector.xml
Labels: enhancement

#83 note app created
  Projects/JavaScript/Noteapp/app.js
  Projects/JavaScript/Noteapp/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#92 Added Diabetes detection project
  Machine-Learning-Models/Indian_Diabetes.ipynb
  Machine-Learning-Models/diabetes.csv
Labels: hacktoberfest, hacktoberfest-accepted

#100 Weather app
  Projects/CarGame/bg.jpg
  Projects/CarGame/blue.png
  Projects/CarGame/index.html
  Projects/CarGame/jumpsound.mp3
  Projects/CarGame/main.js
  Projects/CarGame/race.png
  Projects/CarGame/style.css
  Projects/Weather-show-app/index.html
  Projects/Weather-show-app/script.js
  Projects/Weather-show-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#104 Updated the README file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#108 wine-quality prediction project
  MachineLearningModels/prediction-of-quality-of-wine.ipynb
  MachineLearningModels/winequality-red.csv
Labels: hacktoberfest, hacktoberfest-accepted

#110 Created the Task Management CLI Application using C++
  Projects/C++/.gitignore
  Projects/C++/README.md
  Projects/C++/package.json
  Projects/C++/task.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#114 Add files via upload
  Machine-Learning-Models/titanic_survivers_using_logistic_reg..ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#115 Calculate Number of days between two dates
  Days between two dates/index.html
  Days between two dates/script.js
  Days between two dates/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#123 Tic Tac Toe Game
  Projects/Tic Tac Toe Game/TicTacToe.c
Labels: hacktoberfest, hacktoberfest-accepted

#126 Update about_us_code.html
  AboutUsPage/about_us_code.html
Labels: hacktoberfest, hacktoberfest-accepted

#128 Linear Regression
  LinearRegression.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#140 Spam SMS Detection
  Machine-Learning-Models/Spam_SMS_detection.py.ipynb
  Machine-Learning-Models/sms_data.csv
Labels: hacktoberfest, hacktoberfest-accepted

#142 added game
  Projects/Another one/index.html
  Projects/Another one/javascript.js
  Projects/HTML Projects/Static/Images/10.png
  Projects/HTML Projects/Static/Images/2.png
  Projects/HTML Projects/Static/Images/3.png
  Projects/HTML Projects/Static/Images/4.png
  Projects/HTML Projects/Static/Images/5.png
  Projects/HTML Projects/Static/Images/6.png
  Projects/HTML Projects/Static/Images/7.png
  Projects/HTML Projects/Static/Images/8.png
  Projects/HTML Projects/Static/Images/9.png
  Projects/HTML Projects/Static/Images/A.png
  Projects/HTML Projects/Static/Images/J.png
  Projects/HTML Projects/Static/Images/K.png
  Projects/HTML Projects/Static/Images/Q.png
  Projects/HTML Projects/Static/js/script.js
  Projects/HTML Projects/Static/sounds/aww.mp3
  Projects/HTML Projects/Static/sounds/cash.mp3
  Projects/HTML Projects/Static/sounds/whoosh.mp3
  Projects/HTML Projects/index.html
  Projects/HTML Projects/styles/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#143 added tables
  Programs/Tables/Table_of_1
  Programs/Tables/Table_of_10
  Programs/Tables/Table_of_11
  Programs/Tables/Table_of_12
  Programs/Tables/Table_of_13
  Programs/Tables/Table_of_14
  Programs/Tables/Table_of_15
  Programs/Tables/Table_of_16
  Programs/Tables/Table_of_17
  Programs/Tables/Table_of_18
  Programs/Tables/Table_of_19
  Programs/Tables/Table_of_2
  Programs/Tables/Table_of_20
  Programs/Tables/Table_of_3
  Programs/Tables/Table_of_4
  Programs/Tables/Table_of_5
  Programs/Tables/Table_of_6
  Programs/Tables/Table_of_7
  Programs/Tables/Table_of_8
  Programs/Tables/Table_of_9
Labels: hacktoberfest, hacktoberfest-accepted

#144 added python bots
  Programs/Python-codes-2.0/Library management.py
  Programs/Python-codes-2.0/Webscraping.py
  Programs/Python-codes-2.0/bot for city.py
  Programs/Python-codes-2.0/both for zip codes.py
  Programs/Python-codes-2.0/main.py
  Programs/Python-codes-2.0/new.txt
  Programs/Python-codes-2.0/number guessing.py
  Programs/Python-codes-2.0/oops problem.py
  Programs/Python-codes-2.0/oops.py
  Programs/Python-codes-2.0/pywhat.txt
  Programs/Python-codes-2.0/snake water gun.py
Labels: hacktoberfest, hacktoberfest-accepted

#151 Added meme app files
  kotlin/Meme Share/.gitignore
  kotlin/Meme Share/.idea/.gitignore
  kotlin/Meme Share/.idea/compiler.xml
  kotlin/Meme Share/.idea/gradle.xml
  kotlin/Meme Share/.idea/misc.xml
  kotlin/Meme Share/.idea/vcs.xml
  kotlin/Meme Share/README.md
  kotlin/Meme Share/app/.gitignore
  kotlin/Meme Share/app/build.gradle
  kotlin/Meme Share/app/proguard-rules.pro
  kotlin/Meme Share/app/src/androidTest/java/com/example/memeshare/ExampleInstrumentedTest.kt
  kotlin/Meme Share/app/src/main/AndroidManifest.xml
  kotlin/Meme Share/app/src/main/java/com/example/memeshare/MainActivity.kt
  kotlin/Meme Share/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  kotlin/Meme Share/app/src/main/res/drawable/ic_launcher_background.xml
  kotlin/Meme Share/app/src/main/res/layout/activity_main.xml
  kotlin/Meme Share/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  kotlin/Meme Share/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  kotlin/Meme Share/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  kotlin/Meme Share/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  kotlin/Meme Share/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  kotlin/Meme Share/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  kotlin/Meme Share/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  kotlin/Meme Share/app/src/main/res/values-night/themes.xml
  kotlin/Meme Share/app/src/main/res/values/colors.xml
  kotlin/Meme Share/app/src/main/res/values/strings.xml
  kotlin/Meme Share/app/src/main/res/values/themes.xml
  kotlin/Meme Share/app/src/main/res/xml/backup_rules.xml
  kotlin/Meme Share/app/src/main/res/xml/data_extraction_rules.xml
  kotlin/Meme Share/app/src/test/java/com/example/memeshare/ExampleUnitTest.kt
  kotlin/Meme Share/build.gradle
  kotlin/Meme Share/gradle.properties
  kotlin/Meme Share/gradle/wrapper/gradle-wrapper.jar
  kotlin/Meme Share/gradle/wrapper/gradle-wrapper.properties
  kotlin/Meme Share/gradlew
  kotlin/Meme Share/gradlew.bat
  kotlin/Meme Share/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted

#153 Added the racing game files
  Projects/Racing game/Bgame.css
  Projects/Racing game/README.md
  Projects/Racing game/bGAME.js
  Projects/Racing game/car1.jpeg
  Projects/Racing game/car2.jpeg
  Projects/Racing game/newcar1.png
  Projects/Racing game/newcar2.png
  Projects/Racing game/newtree.png
  Projects/Racing game/racing.html
  Projects/Racing game/tree.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#154 Created a budget manager project
  Projects/Budget Manager/client/build/asset-manifest.json
  Projects/Budget Manager/client/build/favicon.ico
  Projects/Budget Manager/client/build/index.html
  Projects/Budget Manager/client/build/logo192.png
  Projects/Budget Manager/client/build/logo512.png
  Projects/Budget Manager/client/build/manifest.json
  Projects/Budget Manager/client/build/robots.txt
  Projects/Budget Manager/client/build/static/css/main.e9f44403.css
  Projects/Budget Manager/client/build/static/css/main.e9f44403.css.map
  Projects/Budget Manager/client/build/static/js/main.34aada9b.js
  Projects/Budget Manager/client/build/static/js/main.34aada9b.js.LICENSE.txt
  Projects/Budget Manager/client/build/static/js/main.34aada9b.js.map
  Projects/Budget Manager/client/public/favicon.png
  Projects/Budget Manager/client/public/index.html
  Projects/Budget Manager/client/src/App.css
  Projects/Budget Manager/client/src/App.js
  Projects/Budget Manager/client/src/components/AddTransaction.js
  Projects/Budget Manager/client/src/components/Balance.js
  Projects/Budget Manager/client/src/components/Header.js
  Projects/Budget Manager/client/src/components/MainDashboard.js
  Projects/Budget Manager/client/src/components/Transaction.js
  Projects/Budget Manager/client/src/components/TransactionHistory.js
  Projects/Budget Manager/client/src/context/AppReducer.js
  Projects/Budget Manager/client/src/context/GlobalState.js
  Projects/Budget Manager/client/src/index.js
  Projects/Budget Manager/config/config.env
  Projects/Budget Manager/controllers/transactionController.js
  Projects/Budget Manager/db.js
  Projects/Budget Manager/models/TransactionModel.js
  Projects/Budget Manager/routes/transactionRouter.js
  Projects/Budget Manager/server.js
Labels: hacktoberfest, hacktoberfest-accepted

#155 Create Digital clock
  Projects/Python/Digital clock
Labels: hacktoberfest, hacktoberfest-accepted

#156 create countdown_timer
  countdown_timer
Labels: hacktoberfest, hacktoberfest-accepted

#157 added-survey-page
  Projects/Survey form/newform.html
  Projects/Survey form/survey.html
  Projects/coffee menu/coffee.html
  Projects/coffee menu/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#158 added-age-calculator
  Projects/Age Calculator/Age _Calculator.html
Labels: hacktoberfest, hacktoberfest-accepted

#171 added a to do app
  Projects/To-Do app/app.js
  Projects/To-Do app/index.html
  Projects/To-Do app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#170 loop.py
  python/Branching.py
  python/loop.py
Labels: hacktoberfest, hacktoberfest-accepted

#175 Added node-hangman
  Projects/node-hangman/.gitignore
  Projects/node-hangman/README.md
  Projects/node-hangman/colours.json
  Projects/node-hangman/index.js
  Projects/node-hangman/package-lock.json
  Projects/node-hangman/package.json
  Projects/node-hangman/pnpm-lock.yaml
Labels: hacktoberfest, hacktoberfest-accepted
